#
library(MagicQTL)

#I scan the genome of Arabidophsis
rm(list=ls())
phe.name<-c("bolt.to.flower","growth.rate")
nphe<-length(phe.name)
Phe<-read.csv(file="Ara.phe.impute.csv",header=TRUE)
indi<-nrow(Phe)
load(file="Ara.chrs.magic.RData")
load(file="Ara.chrs.kkship.RData")
#
models<-c("Random-A","Random-B","Fixed-A","Fixed-B","IM")
nm<-length(models)
lapply(1:nphe,function(k){

   path<-paste("./Data/Ara/",phe.name[k],"/",sep="")   
   dir.create(path=path,recursive=TRUE,show=FALSE)
   ii<-k+1
   d<-data.frame(y=Phe[,ii],x=rep(1,indi))   
   mc<-1
   tmp<-mclapply(1:nm,function(i){
#   
     s0<-Sys.time()
     cat(phe.name[k],"\n")
     scans<-magicScan(dataframe=d,gen=gen,map=map,kk.eigen=kk.eigen,model=model,nfounders=19,window=5)
     #
     chrnum<-length(scans)
     parr<-lapply(1:chrnum,function(ichr){return(scans[[ichr]]$parr)})
     parr<-do.call(rbind,parr)          
     opfn<-paste(path,models[i],".parr.csv",sep="")
     write.csv(parr,file=opfn,row.names=FALSE)
     blupp<-lapply(1:chrnum,function(ichr){return(scans[[ichr]]$blupp)})
     blupp<-do.call(rbind,blupp)              
     opfn<-paste(path,models[i],".blupp.csv",sep="")
     write.csv(blupp,file=opfn,row.names=FALSE) 
     #
     s1<-Sys.time()
     Time<-data.frame(model=models[i],Start=s0,End=s1,Elapsed=s1-s0)
     write.table(Time,file="Time.Ara.txt",row.names=FALSE,quote=FALSE,sep="\t",append=TRUE)
   },mc.cores=mc)   
})

##
models<-"CIM"
steps<-c(40,27.5,22)
cimpre<-c(".co10",".co15",".co20")
nsteps<-length(steps)
#
lapply(1:nphe,function(k){

   path<-paste("./Data/Ara/",phe.name[k],"/",sep="")   
   dir.create(path=path,recursive=TRUE,show=FALSE)
   ii<-k+1
   d<-data.frame(y=Phe[,ii],x=rep(1,indi))
   
   mc<-1
   tmp<-mclapply(1:nsteps,function(i){   
     cat(phe.name[k],"\n")
     scans<-magicScan(dataframe=d,gen=gen,map=map,kk.eigen=kk.eigen,model=model,nfounders=19,window=5,step=steps[i])
     #
     chrnum<-length(scans)
     parr<-lapply(1:chrnum,function(ichr){return(scans[[ichr]]$parr)})
     parr<-do.call(rbind,parr)          
     opfn<-paste(path,models,cimpre[i],".parr.csv",sep="")
     write.csv(parr,file=opfn,row.names=FALSE)
     #
     blupp<-lapply(1:chrnum,function(ichr){return(scans[[ichr]]$blupp)})
     blupp<-do.call(rbind,blupp)              
     opfn<-paste(path,models,cimpre[i],".blupp.csv",sep="")
     write.csv(blupp,file=opfn,row.names=FALSE)     
   },mc.cores=mc)
})
 
###II,permutation to obtain the threshold values 
rm(list=ls())
source("permutScan.R")
#
phe.name<-c("bolt.to.flower","growth.rate")
nphe<-length(phe.name)
Phe<-read.csv(file="Ara.phe.impute.csv",header=TRUE)
indi<-nrow(Phe)
load(file="Ara.chrs.magic.RData")
load(file="Ara.chrs.kkship.RData")
#
models<-c("Random-A","Random-B","Fixed-A","Fixed-B","IM")
nm<-length(models)
num<-1000
mc<-10
lapply(1:nphe,function(k){
#
   path<-paste("./Data/Ara/",phe.name[k],"/",sep="")   
   dir.create(path=path,recursive=TRUE,show=FALSE)
   ii<-k+1
   d<-data.frame(y=Phe[,ii],x=rep(1,indi))   
   tmp<-lapply(1:nm,function(i){
   pathout<-paste(path,models[i],sep="")
   permutScan(pathout=pathout,dataframe=d,gen=gen,map=map,kk.eigen=kk.eigen,model=models[i],nfounders=19,window=5,num=num,mc=mc)
   }
}
#  
#CIM
models<-"CIM"
steps<-c(40,27.5,22)
cimpre<-c(".co10",".co15",".co20")
nsteps<-length(steps)
num<-1000
mc<-10
lapply(1:nphe,function(k){
#
   path<-paste("./Data/Ara/",phe.name[k],"/",sep="")   
   dir.create(path=path,recursive=TRUE,show=FALSE)
   ii<-k+1
   d<-data.frame(y=Phe[,ii],x=rep(1,indi))   
   tmp<-lapply(1:nsteps,function(i){
   pathout<-paste(path,models,cimpre[i],sep="")
   permutScan(pathout=pathout,dataframe=d,gen=gen,map=map,kk.eigen=kk.eigen,model=models,nfounders=19,window=5,step=steps[i],num=num,mc=mc)
   }
}
#
 